export const AUTH_INFORMATIONS = "AUTH_INFORMATIONS";
export const REMOVE_AUTH_INFORMATIONS = "REMOVE_AUTH_INFORMATIONS";
export const START_ADD_PROFILE_PICRURE = "START_ADD_PROFILE_PICRURE";
export const PROFILE_PICTURE_UPDATED_SUCCESSFULY = "PROFILE_PICTURE_UPDATED_SUCCESSFULY";
export const UPDATE_USER_INFORMATION = "UPDATE_USER_INFORMATION";
