// <auto-generated />
namespace FciFu_Web_Api_2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addQuizzesTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addQuizzesTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202107081116092_addQuizzesTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
